"""add_review_delete_behaviour_on_product_delete

Revision ID: 53f00d8439db
Revises: 603e8cb4c9a0
Create Date: 2026-06-30 01:45:42.904193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '53f00d8439db'
down_revision: Union[str, None] = '603e8cb4c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###