// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AdminAdminCreateProductData,
  AdminAdminCreateProductErrors,
  AdminAdminCreateProductResponses,
  AdminAdminDeleteProductData,
  AdminAdminDeleteProductErrors,
  AdminAdminDeleteProductResponses,
  AdminAdminDeleteReviewData,
  AdminAdminDeleteReviewErrors,
  AdminAdminDeleteReviewResponses,
  AdminAdminListProductsData,
  AdminAdminListProductsResponses,
  AdminAdminListReviewsData,
  AdminAdminListReviewsResponses,
  AuthAuthJwtLoginData,
  AuthAuthJwtLoginErrors,
  AuthAuthJwtLoginResponses,
  AuthAuthJwtLogoutData,
  AuthAuthJwtLogoutErrors,
  AuthAuthJwtLogoutResponses,
  AuthRegisterRegisterData,
  AuthRegisterRegisterErrors,
  AuthRegisterRegisterResponses,
  ProductsGetProductData,
  ProductsGetProductErrors,
  ProductsGetProductResponses,
  ProductsListProductsData,
  ProductsListProductsResponses,
  ReviewsCreateReviewData,
  ReviewsCreateReviewErrors,
  ReviewsCreateReviewResponses,
  ReviewsDeleteReviewData,
  ReviewsDeleteReviewErrors,
  ReviewsDeleteReviewResponses,
  ReviewsGetMyReviewsData,
  ReviewsGetMyReviewsResponses,
  ReviewsUpdateReviewData,
  ReviewsUpdateReviewErrors,
  ReviewsUpdateReviewResponses,
  UsersUsersCurrentUserData,
  UsersUsersCurrentUserErrors,
  UsersUsersCurrentUserResponses,
  UsersUsersDeleteUserData,
  UsersUsersDeleteUserErrors,
  UsersUsersDeleteUserResponses,
  UsersUsersPatchCurrentUserData,
  UsersUsersPatchCurrentUserErrors,
  UsersUsersPatchCurrentUserResponses,
  UsersUsersPatchUserData,
  UsersUsersPatchUserErrors,
  UsersUsersPatchUserResponses,
  UsersUsersUserData,
  UsersUsersUserErrors,
  UsersUsersUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Auth:Jwt.Login
 */
export const authAuthJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthAuthJwtLoginData, ThrowOnError>,
): RequestResult<
  AuthAuthJwtLoginResponses,
  AuthAuthJwtLoginErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthAuthJwtLoginResponses,
    AuthAuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authAuthJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthAuthJwtLogoutData, ThrowOnError>,
): RequestResult<
  AuthAuthJwtLogoutResponses,
  AuthAuthJwtLogoutErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    AuthAuthJwtLogoutResponses,
    AuthAuthJwtLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const authRegisterRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterRegisterData, ThrowOnError>,
): RequestResult<
  AuthRegisterRegisterResponses,
  AuthRegisterRegisterErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthRegisterRegisterResponses,
    AuthRegisterRegisterErrors,
    ThrowOnError
  >({
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersUsersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersUsersCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersUsersCurrentUserResponses,
  UsersUsersCurrentUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    UsersUsersCurrentUserResponses,
    UsersUsersCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersUsersPatchCurrentUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersUsersPatchCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersUsersPatchCurrentUserResponses,
  UsersUsersPatchCurrentUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UsersUsersPatchCurrentUserResponses,
    UsersUsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersUsersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersDeleteUserData, ThrowOnError>,
): RequestResult<
  UsersUsersDeleteUserResponses,
  UsersUsersDeleteUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    UsersUsersDeleteUserResponses,
    UsersUsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUsersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersUserData, ThrowOnError>,
): RequestResult<UsersUsersUserResponses, UsersUsersUserErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsersUsersUserResponses,
    UsersUsersUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersUsersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersPatchUserData, ThrowOnError>,
): RequestResult<
  UsersUsersPatchUserResponses,
  UsersUsersPatchUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UsersUsersPatchUserResponses,
    UsersUsersPatchUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Products
 */
export const productsListProducts = <ThrowOnError extends boolean = false>(
  options?: Options<ProductsListProductsData, ThrowOnError>,
): RequestResult<ProductsListProductsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ProductsListProductsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/products/", ...options });

/**
 * Get Product
 */
export const productsGetProduct = <ThrowOnError extends boolean = false>(
  options: Options<ProductsGetProductData, ThrowOnError>,
): RequestResult<
  ProductsGetProductResponses,
  ProductsGetProductErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProductsGetProductResponses,
    ProductsGetProductErrors,
    ThrowOnError
  >({ url: "/api/products/{product_id}", ...options });

/**
 * Create Review
 */
export const reviewsCreateReview = <ThrowOnError extends boolean = false>(
  options: Options<ReviewsCreateReviewData, ThrowOnError>,
): RequestResult<
  ReviewsCreateReviewResponses,
  ReviewsCreateReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ReviewsCreateReviewResponses,
    ReviewsCreateReviewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reviews/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Reviews
 */
export const reviewsGetMyReviews = <ThrowOnError extends boolean = false>(
  options?: Options<ReviewsGetMyReviewsData, ThrowOnError>,
): RequestResult<ReviewsGetMyReviewsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ReviewsGetMyReviewsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reviews/me",
    ...options,
  });

/**
 * Delete Review
 */
export const reviewsDeleteReview = <ThrowOnError extends boolean = false>(
  options: Options<ReviewsDeleteReviewData, ThrowOnError>,
): RequestResult<
  ReviewsDeleteReviewResponses,
  ReviewsDeleteReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ReviewsDeleteReviewResponses,
    ReviewsDeleteReviewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reviews/{review_id}",
    ...options,
  });

/**
 * Update Review
 */
export const reviewsUpdateReview = <ThrowOnError extends boolean = false>(
  options: Options<ReviewsUpdateReviewData, ThrowOnError>,
): RequestResult<
  ReviewsUpdateReviewResponses,
  ReviewsUpdateReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReviewsUpdateReviewResponses,
    ReviewsUpdateReviewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reviews/{review_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Admin List Products
 */
export const adminAdminListProducts = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAdminListProductsData, ThrowOnError>,
): RequestResult<AdminAdminListProductsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AdminAdminListProductsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/admin/products",
    ...options,
  });

/**
 * Admin Create Product
 */
export const adminAdminCreateProduct = <ThrowOnError extends boolean = false>(
  options: Options<AdminAdminCreateProductData, ThrowOnError>,
): RequestResult<
  AdminAdminCreateProductResponses,
  AdminAdminCreateProductErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminAdminCreateProductResponses,
    AdminAdminCreateProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/admin/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Admin List Reviews
 */
export const adminAdminListReviews = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAdminListReviewsData, ThrowOnError>,
): RequestResult<AdminAdminListReviewsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AdminAdminListReviewsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/admin/reviews",
    ...options,
  });

/**
 * Admin Delete Product
 */
export const adminAdminDeleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<AdminAdminDeleteProductData, ThrowOnError>,
): RequestResult<
  AdminAdminDeleteProductResponses,
  AdminAdminDeleteProductErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminAdminDeleteProductResponses,
    AdminAdminDeleteProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/admin/products/{product_id}",
    ...options,
  });

/**
 * Admin Delete Review
 */
export const adminAdminDeleteReview = <ThrowOnError extends boolean = false>(
  options: Options<AdminAdminDeleteReviewData, ThrowOnError>,
): RequestResult<
  AdminAdminDeleteReviewResponses,
  AdminAdminDeleteReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminAdminDeleteReviewResponses,
    AdminAdminDeleteReviewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/admin/reviews/{review_id}",
    ...options,
  });
