// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthAuthJwtLoginData,
  AuthAuthJwtLoginErrors,
  AuthAuthJwtLoginResponses,
  AuthAuthJwtLogoutData,
  AuthAuthJwtLogoutErrors,
  AuthAuthJwtLogoutResponses,
  AuthRegisterRegisterData,
  AuthRegisterRegisterErrors,
  AuthRegisterRegisterResponses,
  UsersUsersCurrentUserData,
  UsersUsersCurrentUserErrors,
  UsersUsersCurrentUserResponses,
  UsersUsersDeleteUserData,
  UsersUsersDeleteUserErrors,
  UsersUsersDeleteUserResponses,
  UsersUsersPatchCurrentUserData,
  UsersUsersPatchCurrentUserErrors,
  UsersUsersPatchCurrentUserResponses,
  UsersUsersPatchUserData,
  UsersUsersPatchUserErrors,
  UsersUsersPatchUserResponses,
  UsersUsersUserData,
  UsersUsersUserErrors,
  UsersUsersUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Auth:Jwt.Login
 */
export const authAuthJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthAuthJwtLoginData, ThrowOnError>,
): RequestResult<
  AuthAuthJwtLoginResponses,
  AuthAuthJwtLoginErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthAuthJwtLoginResponses,
    AuthAuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authAuthJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthAuthJwtLogoutData, ThrowOnError>,
): RequestResult<
  AuthAuthJwtLogoutResponses,
  AuthAuthJwtLogoutErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    AuthAuthJwtLogoutResponses,
    AuthAuthJwtLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const authRegisterRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterRegisterData, ThrowOnError>,
): RequestResult<
  AuthRegisterRegisterResponses,
  AuthRegisterRegisterErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthRegisterRegisterResponses,
    AuthRegisterRegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersUsersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersUsersCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersUsersCurrentUserResponses,
  UsersUsersCurrentUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    UsersUsersCurrentUserResponses,
    UsersUsersCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersUsersPatchCurrentUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersUsersPatchCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersUsersPatchCurrentUserResponses,
  UsersUsersPatchCurrentUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UsersUsersPatchCurrentUserResponses,
    UsersUsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersUsersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersDeleteUserData, ThrowOnError>,
): RequestResult<
  UsersUsersDeleteUserResponses,
  UsersUsersDeleteUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    UsersUsersDeleteUserResponses,
    UsersUsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUsersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersUserData, ThrowOnError>,
): RequestResult<UsersUsersUserResponses, UsersUsersUserErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsersUsersUserResponses,
    UsersUsersUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersUsersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersPatchUserData, ThrowOnError>,
): RequestResult<
  UsersUsersPatchUserResponses,
  UsersUsersPatchUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UsersUsersPatchUserResponses,
    UsersUsersPatchUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
