// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AdminReviewRead
 */
export type AdminReviewRead = {
  /**
   * Rating
   */
  rating: number;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Product Title
   */
  product_title: string;
  /**
   * User Id
   */
  user_id: string;
  /**
   * User Name
   */
  user_name: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * PaginatedProductList
 */
export type PaginatedProductList = {
  /**
   * Items
   */
  items: Array<ProductListItem>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Image Url
   */
  image_url?: string | null;
};

/**
 * ProductDetail
 */
export type ProductDetail = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reviews
   */
  reviews: Array<ReviewRead>;
};

/**
 * ProductListItem
 */
export type ProductListItem = {
  /**
   * Id
   */
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Image Url
   */
  image_url: string | null;
  /**
   * Average Rating
   */
  average_rating: number;
  /**
   * Review Count
   */
  review_count: number;
};

/**
 * ProductRead
 */
export type ProductRead = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
  /**
   * Rating
   */
  rating: number;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Product Id
   */
  product_id: number;
};

/**
 * ReviewRead
 */
export type ReviewRead = {
  /**
   * Rating
   */
  rating: number;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  /**
   * User Id
   */
  user_id: string;
  /**
   * User Name
   */
  user_name: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ReviewUpdate
 */
export type ReviewUpdate = {
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Comment
   */
  comment?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Name
   */
  name?: string;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Name
   */
  name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthAuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/api/auth/jwt/login";
};

export type AuthAuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthAuthJwtLoginError =
  AuthAuthJwtLoginErrors[keyof AuthAuthJwtLoginErrors];

export type AuthAuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthAuthJwtLoginResponse =
  AuthAuthJwtLoginResponses[keyof AuthAuthJwtLoginResponses];

export type AuthAuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/jwt/logout";
};

export type AuthAuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthAuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthRegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/auth/register";
};

export type AuthRegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthRegisterRegisterError =
  AuthRegisterRegisterErrors[keyof AuthRegisterRegisterErrors];

export type AuthRegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type AuthRegisterRegisterResponse =
  AuthRegisterRegisterResponses[keyof AuthRegisterRegisterResponses];

export type UsersUsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UsersUsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersUsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersCurrentUserResponse =
  UsersUsersCurrentUserResponses[keyof UsersUsersCurrentUserResponses];

export type UsersUsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UsersUsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersPatchCurrentUserError =
  UsersUsersPatchCurrentUserErrors[keyof UsersUsersPatchCurrentUserErrors];

export type UsersUsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersPatchCurrentUserResponse =
  UsersUsersPatchCurrentUserResponses[keyof UsersUsersPatchCurrentUserResponses];

export type UsersUsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersUsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersDeleteUserError =
  UsersUsersDeleteUserErrors[keyof UsersUsersDeleteUserErrors];

export type UsersUsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersUsersDeleteUserResponse =
  UsersUsersDeleteUserResponses[keyof UsersUsersDeleteUserResponses];

export type UsersUsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersUsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersUserError =
  UsersUsersUserErrors[keyof UsersUsersUserErrors];

export type UsersUsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersUserResponse =
  UsersUsersUserResponses[keyof UsersUsersUserResponses];

export type UsersUsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersUsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersPatchUserError =
  UsersUsersPatchUserErrors[keyof UsersUsersPatchUserErrors];

export type UsersUsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersPatchUserResponse =
  UsersUsersPatchUserResponses[keyof UsersUsersPatchUserResponses];

export type ProductsListProductsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     *
     * Search product titles
     */
    search?: string | null;
    /**
     * Min Rating
     *
     * Minimum average rating
     */
    min_rating?: number | null;
    /**
     * Max Rating
     *
     * Maximum average rating
     */
    max_rating?: number | null;
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number;
  };
  url: "/api/products/";
};

export type ProductsListProductsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProductsListProductsError =
  ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedProductList;
};

export type ProductsListProductsResponse =
  ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type ProductsGetProductData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: "/api/products/{product_id}";
};

export type ProductsGetProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProductsGetProductError =
  ProductsGetProductErrors[keyof ProductsGetProductErrors];

export type ProductsGetProductResponses = {
  /**
   * Successful Response
   */
  200: ProductDetail;
};

export type ProductsGetProductResponse =
  ProductsGetProductResponses[keyof ProductsGetProductResponses];

export type ReviewsCreateReviewData = {
  body: ReviewCreate;
  path?: never;
  query?: never;
  url: "/api/reviews/";
};

export type ReviewsCreateReviewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReviewsCreateReviewError =
  ReviewsCreateReviewErrors[keyof ReviewsCreateReviewErrors];

export type ReviewsCreateReviewResponses = {
  /**
   * Successful Response
   */
  201: ReviewRead;
};

export type ReviewsCreateReviewResponse =
  ReviewsCreateReviewResponses[keyof ReviewsCreateReviewResponses];

export type ReviewsGetMyReviewsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/reviews/me";
};

export type ReviewsGetMyReviewsResponses = {
  /**
   * Response Reviews-Get My Reviews
   *
   * Successful Response
   */
  200: Array<ReviewRead>;
};

export type ReviewsGetMyReviewsResponse =
  ReviewsGetMyReviewsResponses[keyof ReviewsGetMyReviewsResponses];

export type ReviewsDeleteReviewData = {
  body?: never;
  path: {
    /**
     * Review Id
     */
    review_id: number;
  };
  query?: never;
  url: "/api/reviews/{review_id}";
};

export type ReviewsDeleteReviewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReviewsDeleteReviewError =
  ReviewsDeleteReviewErrors[keyof ReviewsDeleteReviewErrors];

export type ReviewsDeleteReviewResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ReviewsDeleteReviewResponse =
  ReviewsDeleteReviewResponses[keyof ReviewsDeleteReviewResponses];

export type ReviewsUpdateReviewData = {
  body: ReviewUpdate;
  path: {
    /**
     * Review Id
     */
    review_id: number;
  };
  query?: never;
  url: "/api/reviews/{review_id}";
};

export type ReviewsUpdateReviewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReviewsUpdateReviewError =
  ReviewsUpdateReviewErrors[keyof ReviewsUpdateReviewErrors];

export type ReviewsUpdateReviewResponses = {
  /**
   * Successful Response
   */
  200: ReviewRead;
};

export type ReviewsUpdateReviewResponse =
  ReviewsUpdateReviewResponses[keyof ReviewsUpdateReviewResponses];

export type AdminAdminListProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/admin/products";
};

export type AdminAdminListProductsResponses = {
  /**
   * Response Admin-Admin List Products
   *
   * Successful Response
   */
  200: Array<ProductRead>;
};

export type AdminAdminListProductsResponse =
  AdminAdminListProductsResponses[keyof AdminAdminListProductsResponses];

export type AdminAdminCreateProductData = {
  body: ProductCreate;
  path?: never;
  query?: never;
  url: "/api/admin/products";
};

export type AdminAdminCreateProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdminAdminCreateProductError =
  AdminAdminCreateProductErrors[keyof AdminAdminCreateProductErrors];

export type AdminAdminCreateProductResponses = {
  /**
   * Successful Response
   */
  201: ProductRead;
};

export type AdminAdminCreateProductResponse =
  AdminAdminCreateProductResponses[keyof AdminAdminCreateProductResponses];

export type AdminAdminListReviewsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/admin/reviews";
};

export type AdminAdminListReviewsResponses = {
  /**
   * Response Admin-Admin List Reviews
   *
   * Successful Response
   */
  200: Array<AdminReviewRead>;
};

export type AdminAdminListReviewsResponse =
  AdminAdminListReviewsResponses[keyof AdminAdminListReviewsResponses];

export type AdminAdminDeleteProductData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: "/api/admin/products/{product_id}";
};

export type AdminAdminDeleteProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdminAdminDeleteProductError =
  AdminAdminDeleteProductErrors[keyof AdminAdminDeleteProductErrors];

export type AdminAdminDeleteProductResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AdminAdminDeleteProductResponse =
  AdminAdminDeleteProductResponses[keyof AdminAdminDeleteProductResponses];

export type AdminAdminDeleteReviewData = {
  body?: never;
  path: {
    /**
     * Review Id
     */
    review_id: number;
  };
  query?: never;
  url: "/api/admin/reviews/{review_id}";
};

export type AdminAdminDeleteReviewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdminAdminDeleteReviewError =
  AdminAdminDeleteReviewErrors[keyof AdminAdminDeleteReviewErrors];

export type AdminAdminDeleteReviewResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AdminAdminDeleteReviewResponse =
  AdminAdminDeleteReviewResponses[keyof AdminAdminDeleteReviewResponses];
